name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v2
        with:
          ref: master # This ensures you're always checking out the master branch. Remove if you want to checkout the triggering commit.

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and check with Gradle
        run: ./gradlew check coverage

      - name: Run repository-wide tests (Linux only)
        if: runner.os == 'Linux'
        run: ./run-checks.sh
        working-directory: ${{ github.workspace }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/coverage.xml # Update this path if your coverage report is generated elsewhere.
          flags: unittests # Optional: Use if you want to categorize coverage reports.
          name: codecov-umbrella # Optional: Custom name for the upload.
